### ISSUE TITLE
Winning check bug

### ISSUE THREAD

**Issue by mxzoom** [kisinga/tictactoe#1]
Hello! The mechanism of checking for winning by filling in the second or third vertical column works incorrectly. Example on the screenshot.
![image](https://user-images.githubusercontent.com/19909325/177745254-f4aaa0ab-183d-4351-befe-1bef122ed432.png)

**Comment by kisinga** [comment]
@mxzoom 
Check out this [new repo](https://github.com/kisinga/go-htmx-tictactoe) where I've done something similar using slightly different tech
